kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "aws-node-termination-handler.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "aws-node-termination-handler.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "aws-node-termination-handler.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
