{{- if and .Values.enableSqsTerminationDraining (and .Values.podDisruptionBudget (gt (int .Values.replicas) 1)) }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "aws-node-termination-handler.fullname" . }}
  labels:
    {{- include "aws-node-termination-handler.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "aws-node-termination-handler.selectorLabels" . | nindent 6 }}
  {{- toYaml .Values.podDisruptionBudget | nindent 2 }}
{{- end }}
