{{- if .Values.podMonitor.create }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ template "aws-node-termination-handler.fullname" . }}
  {{- if .Values.podMonitor.namespace }}
  namespace: {{ .Values.podMonitor.namespace }}
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    {{- include "aws-node-termination-handler.labels" . | nindent 4 }}
  {{- with .Values.podMonitor.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  jobLabel: {{ include "aws-node-termination-handler.name" . }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  podMetricsEndpoints:
  - interval: {{ .Values.podMonitor.interval }}
    path: /metrics
    port: http-metrics
  sampleLimit: {{ .Values.podMonitor.sampleLimit }}
  selector:
    matchLabels:
      {{- include "aws-node-termination-handler.selectorLabels" . | nindent 6 }}
{{- end }}
