kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "squid.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "squid.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "squid.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
