apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "squid.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
{{ include "squid.labels" . | indent 4 }}
