---
language: minimal

services:
- docker

env:
- KUBE_VERSION=1.17
- KUBE_VERSION=1.16
- KUBE_VERSION=1.15
- KUBE_VERSION=1.14
- KUBE_VERSION=1.13
- KUBE_VERSION=1.12
- KUBE_VERSION=1.11

script: test/k8s-local-cluster-test/run-test -v $KUBE_VERSION

matrix:
  include:
    - stage: Test
      language: go
      go: "1.13.x"
      script: make unit-test
      env: GO111MODULE=on
      after_success: bash <(curl -s https://codecov.io/bash)
    - stage: Test
      script: test/go-report-card-test/run-report-card-test.sh
      env: GO_REPORT_CARD=true
    - stage: Test
      if: type = push AND branch = master AND env(GITHUB_TOKEN) IS present
      script: test/license-test/run-license-test.sh
      env: LICENSE_TEST=true
    - stage: Test
      script: make helm-sync-test
      env: HELM_SYNC_TEST=true
    - stage: Deploy
      if: type = push AND env(DOCKER_USERNAME) IS present
      script: make sync-readme-to-dockerhub
    - stage: Deploy
      if: type = push AND tag =~ /^v\d+\.\d+(\.\d+)?(-\S*)?$/ AND env(DOCKER_USERNAME) IS present
      script: make docker-build-and-push
    - stage: Deploy
      if: type = push AND tag =~ /^v\d+\.\d+(\.\d+)?(-\S*)?$/ AND env(DOCKER_USERNAME) IS present
      script: make release

