AWSTemplateFormatVersion: "2010-09-09"
Description: Resources used by AWS Node Termination Handler v2
Parameters:
  ClusterName:
    Type: String
    Description: "EKS cluster name"
Resources:
  Nthv2ControllerPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "Nthv2ControllerPolicy-${ClusterName}"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Resource: "*"
            Action:
              - autoscaling:CompleteLifecycleAction
              - autoscaling:DescribeAutoScalingInstances
              - autoscaling:DescribeTags
              - ec2:DescribeInstances
              - sqs:DeleteMessage
              - sqs:ReceiveMessage
