kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "ec2-metadata-test-proxy.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "ec2-metadata-test-proxy.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "ec2-metadata-test-proxy.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
