serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::99999999:role/nth-role

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

enableSqsTerminationDraining: true
