# Default values for aws-node-termination-handler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: amazon/aws-node-termination-handler
  tag: v1.4.0
  pullPolicy: IfNotPresent
  pullSecrets: []

securityContext:
  runAsUserID: 1000
  runAsGroupID: 1000

nameOverride: ""
fullnameOverride: ""

priorityClassName: system-node-critical

podAnnotations: {}

resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "100m"

## enableSpotInterruptionDraining If true, drain nodes when the spot interruption termination notice is receieved
enableSpotInterruptionDraining: ""

## enableScheduledEventDraining [EXPERIMENTAL] If true, drain nodes before the maintenance window starts for an EC2 instance scheduled event
enableScheduledEventDraining: ""

## dryRun tells node-termination-handler to only log calls to kubernetes control plane
dryRun: false

# deleteLocalData tells kubectl to continue even if there are pods using
# emptyDir (local data that will be deleted when the node is drained).
deleteLocalData: ""

# ignoreDaemonSets causes kubectl to skip Daemon Set managed pods.
ignoreDaemonSets: ""

# gracePeriod (DEPRECATED - use podTerminationGracePeriod instead) is time in seconds given to each pod to terminate gracefully.
# If negative, the default value specified in the pod will be used.
gracePeriod: ""
podTerminationGracePeriod: ""

# nodeTerminationGracePeriod specifies the period of time in seconds given to each NODE to terminate gracefully. Node draining will be scheduled based on this value to optimize the amount of compute time, but still safely drain the node before an event.
nodeTerminationGracePeriod: ""

# webhookURL if specified, posts event data to URL upon instance interruption action.
webhookURL: ""

# webhookProxy if specified, uses this HTTP(S) proxy configuration.
webhookProxy: ""

# webhookHeaders if specified, replaces the default webhook headers.
webhookHeaders: ""

# webhookTemplate if specified, replaces the default webhook message template.
webhookTemplate: ""

# instanceMetadataURL is used to override the default metadata URL (default: http://169.254.169.254:80)
instanceMetadataURL: ""

# (TESTING USE): Mount path for uptime file
procUptimeFile: "/proc/uptime"

# nodeSelector tells the daemonset where to place the node-termination-handler
# pods. By default, this value is empty and every node will receive a pod.
nodeSelector: {}

nodeSelectorTermsOs: ""
nodeSelectorTermsArch: ""

tolerations: 
  - operator: "Exists"

affinity: {}

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use. If namenot set and create is true,
  # a name is generated using fullname template
  name:
  annotations: {}
    # eks.amazonaws.com/role-arn: arn:aws:iam::AWS_ACCOUNT_ID:role/IAM_ROLE_NAME

rbac:
  # rbac.pspEnabled: `true` if PodSecurityPolicy resources should be created
  pspEnabled: true

dnsPolicy: "ClusterFirstWithHostNet"
