#!/bin/bash
set -euo pipefail

if [[ -z "${ECR_REGISTRY}" ]]; then
    echo "The env var ECR_REGISTRY must be set"
    exit 1
fi

docker login --username AWS -p="$(docker run --rm --env-file <(env | grep AWS) -i amazon/aws-cli ecr-public get-login-password --region us-east-1)" ${ECR_REGISTRY}
