nameOverride: ""
fullnameOverride: ""
priorityClassName: system-node-critical
podAnnotations: {}
rbac:
    pspEnabled: true
serviceAccount:
    name: ls-sa
    create: true
    annotations: {}

label: localstack
port: 80
containerPort: 4566
image:
  repository: localstack/localstack
  tag: 3.0.2
  pullPolicy: IfNotPresent
tolerations:
  - operator: "Exists"
nodeSelector: {}
services: "events,sqs,ec2"
defaultRegion: "us-east-1"