kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-termination-handler
subjects:
- kind: ServiceAccount
  name: node-termination-handler
roleRef:
  kind: ClusterRole
  name: node-termination-handler
  apiGroup: rbac.authorization.k8s.io